name: Birth-Greeting CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Frontend build
      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      # Backend build
      - name: Build Backend
        run: |
          cd backend
          npm install

      # Docker login
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push frontend Docker
      - name: Push Frontend Docker
        run: |
          docker build -t ${{ secrets.tbiruh1221 }}/birth-frontend:latest ./frontend
          docker push ${{ secrets.tbiruh1221 }}/birth-frontend:latest

      # Build and push backend Docker
      - name: Push Backend Docker
        run: |
          docker build -t ${{ secrets.tbiruh1221 }}/birth-backend:latest ./backend
          docker push ${{ secrets.tbiruh1221 }}/birth-backend:latest
